import { readFile, readdir } from 'fs/promises';
import { join, dirname } from 'path';
import { homedir } from 'os';
import { discoverAllSessions } from './providers';
import { parseSession } from './parser';
import type { SessionTimeline, ToolCallEvent } from '$lib/types/timeline';
import { estimateCost, pricingForModel } from '$lib/utils/cost';

/**
 * Approximate chars-per-token for markdown content (mix of English prose and code).
 * Anthropic's tokenizer is not public, so this is heuristic — within ±15% of truth
 * which is good enough for "is this skill worth keeping" decisions.
 */
const CHARS_PER_TOKEN = 3.5;

/**
 * Rough token cost of a single MCP tool entry in the system prompt:
 * tool name + JSON schema + description. Spans 80-300 tokens in practice;
 * 150 is a reasonable middle.
 */
const TOKENS_PER_MCP_TOOL = 150;

const HOME = homedir();

export interface OverheadFile {
	name: string;
	/** Display path (with `~` substitution). Empty for synthesized entries (MCP). */
	path: string;
	tokensEst: number;
	/** Times this resource was actually invoked over the analysis window. */
	invocationCount: number;
	lastUsed?: string;
	/**
	 * Total $ generated by this skill — sum of all events' cost from invocation
	 * up to the next user message (the "skill's turn"). Only populated for skills.
	 */
	costGenerated?: number;
	/** Tokens spent within the skill's attributed turns (input+output+cache). */
	tokensGenerated?: number;
	/** Inline content (SKILL.md / CLAUDE.md) for click-to-view. Capped at 64KB. */
	content?: string;
}

export interface EffortDistribution {
	low: number;
	medium: number;
	high: number;
	/** Configured value from settings.json (the "default"). */
	configured: string;
}

export interface OverheadHook {
	event: string;
	matcher?: string;
	commandCount: number;
}

export interface OverheadRecommendation {
	kind: 'unused-skill' | 'unused-mcp' | 'large-claude-md' | 'effort';
	title: string;
	detail: string;
	/** Estimated savings per month at current usage pace (USD). */
	monthlySavingsUsd: number;
	severity: 'info' | 'warning' | 'critical';
}

export interface OverheadAnalysis {
	claudeMd: OverheadFile[];
	skills: OverheadFile[];
	mcpServers: OverheadFile[];
	hooks: OverheadHook[];
	effortLevel: string;
	/** Distribution of "observed effort" across recent sessions (heuristic from thinking volume). */
	effort: EffortDistribution;
	totals: {
		setupTokens: number;
		sessionsAnalyzed: number;
		daysAnalyzed: number;
		sessionsPerMonth: number;
		/** Per-session cost on a fresh load (cache write rate). */
		costPerSessionFresh: number;
		/** Per-session cost when the cache is warm (cache read rate). */
		costPerSessionCached: number;
		/** Projected monthly cost if every session paid cached overhead. */
		monthlyCachedCost: number;
	};
	recommendations: OverheadRecommendation[];
}

export interface SessionOverhead {
	claudeMd: OverheadFile[];
	skillsInvoked: Array<{
		name: string;
		count: number;
		costGenerated: number;
		tokensGenerated: number;
	}>;
	mcpUsed: Array<{ server: string; count: number; tools: string[] }>;
	effort: { bucket: 'low' | 'medium' | 'high'; thinkingChars: number; ratio: number };
}

const cache = new Map<string, { data: OverheadAnalysis; timestamp: number }>();
const CACHE_TTL = 120_000;

async function readIfExists(path: string): Promise<string | null> {
	try {
		return await readFile(path, 'utf-8');
	} catch {
		return null;
	}
}

function tokensFromChars(chars: number): number {
	return Math.round(chars / CHARS_PER_TOKEN);
}

/**
 * The harness injects a user_message containing the SKILL.md body right after a
 * Skill tool_use. It looks like a real user reply but isn't — treat it as part
 * of the skill's turn so we don't reset attribution on it.
 */
function isHarnessSkillLoadMessage(text: string): boolean {
	return /^Base directory for this skill:/.test(text);
}

function displayPath(p: string): string {
	return p.startsWith(HOME) ? '~' + p.slice(HOME.length) : p;
}

const MAX_INLINED_CONTENT = 64_000;

/** Walk up from each session cwd and collect every CLAUDE.md that applies. */
async function scanClaudeMd(cwds: string[]): Promise<OverheadFile[]> {
	const candidates = new Set<string>([
		join(HOME, 'CLAUDE.md'),
		join(HOME, '.claude', 'CLAUDE.md')
	]);
	for (const cwd of cwds) {
		let cur = cwd;
		const stop = dirname(HOME);
		while (cur && cur !== '/' && cur !== stop) {
			candidates.add(join(cur, 'CLAUDE.md'));
			candidates.add(join(cur, '.claude', 'CLAUDE.md'));
			const parent = dirname(cur);
			if (parent === cur) break;
			cur = parent;
		}
	}

	const out: OverheadFile[] = [];
	for (const p of candidates) {
		const content = await readIfExists(p);
		if (content === null || content.length === 0) continue;
		out.push({
			name: displayPath(p),
			path: p,
			tokensEst: tokensFromChars(content.length),
			invocationCount: 0,
			content: content.slice(0, MAX_INLINED_CONTENT)
		});
	}
	out.sort((a, b) => b.tokensEst - a.tokensEst);
	return out;
}

async function scanSkills(): Promise<OverheadFile[]> {
	const skillsDir = join(HOME, '.claude', 'skills');
	let entries: string[];
	try {
		entries = await readdir(skillsDir);
	} catch {
		return [];
	}
	const out: OverheadFile[] = [];
	for (const dirName of entries) {
		const skillFile = join(skillsDir, dirName, 'SKILL.md');
		const content = await readIfExists(skillFile);
		if (content === null) continue;
		out.push({
			name: dirName,
			path: displayPath(skillFile),
			tokensEst: tokensFromChars(content.length),
			invocationCount: 0,
			content: content.slice(0, MAX_INLINED_CONTENT),
			costGenerated: 0,
			tokensGenerated: 0
		});
	}
	out.sort((a, b) => b.tokensEst - a.tokensEst);
	return out;
}

interface UserSettings {
	effortLevel: string;
	hooks: OverheadHook[];
}

async function readSettings(): Promise<UserSettings> {
	const userSettings = await readIfExists(join(HOME, '.claude', 'settings.json'));
	let parsed: Record<string, unknown> = {};
	try {
		parsed = userSettings ? JSON.parse(userSettings) : {};
	} catch {
		parsed = {};
	}

	const hooks: OverheadHook[] = [];
	const hooksRaw = parsed.hooks as Record<string, unknown> | undefined;
	if (hooksRaw && typeof hooksRaw === 'object') {
		for (const [event, configs] of Object.entries(hooksRaw)) {
			if (!Array.isArray(configs)) continue;
			for (const cfg of configs as Array<{ matcher?: string; hooks?: unknown[] }>) {
				const cmds = Array.isArray(cfg.hooks) ? cfg.hooks.length : 0;
				hooks.push({ event, matcher: cfg.matcher, commandCount: cmds });
			}
		}
	}

	return {
		effortLevel: typeof parsed.effortLevel === 'string' ? parsed.effortLevel : 'medium',
		hooks
	};
}

export async function analyzeOverhead(daysBack = 30): Promise<OverheadAnalysis> {
	const cacheKey = String(daysBack);
	const cached = cache.get(cacheKey);
	if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
		return cached.data;
	}

	const { sessions } = await discoverAllSessions();
	const cutoff = new Date(Date.now() - daysBack * 86400000);
	const recent = sessions.filter((s) => new Date(s.startedAt) >= cutoff);

	const cwds = [...new Set(recent.map((s) => s.cwd).filter((c): c is string => !!c))];

	const [claudeMd, skills, settings] = await Promise.all([
		scanClaudeMd(cwds),
		scanSkills(),
		readSettings()
	]);

	// Walk recent sessions to count invocations + attribute cost per skill.
	// Filter to claude-code first then take 200 most-recent — Skill / mcp__ tool
	// calls only exist in this provider's data.
	const sample = recent.filter((s) => s.provider === 'claude-code').slice(0, 200);

	interface SkillUsage {
		count: number;
		lastUsed: string;
		tokensGenerated: number;
		costGenerated: number;
	}
	const skillUsage = new Map<string, SkillUsage>();
	const mcpUsage = new Map<
		string,
		{ count: number; lastUsed: string; tools: Set<string> }
	>();
	const effortBuckets: EffortDistribution = { low: 0, medium: 0, high: 0, configured: '' };

	for (const s of sample) {
		let timeline;
		try {
			timeline = await parseSession(s.filePath, s.sessionId, s.project);
		} catch {
			continue;
		}

		// Skill cost attribution: from each Skill tool_use up to the next
		// user_message (or another Skill, or end of session) is "the skill's turn".
		let activeSkill: string | null = null;
		let activeTokens = 0;
		let activeCost = 0;

		const flush = () => {
			if (activeSkill) {
				const u = skillUsage.get(activeSkill);
				if (u) {
					u.tokensGenerated += activeTokens;
					u.costGenerated += activeCost;
				}
			}
			activeSkill = null;
			activeTokens = 0;
			activeCost = 0;
		};

		// Observed-effort signal: count thinking events. Anthropic returns
		// thinking text encrypted (empty + signature), so we can't measure
		// volume — but presence/count of thinking events still indicates
		// extended thinking actually ran.
		let sessionThinkingEvents = 0;
		let sessionThinkingChars = 0;

		for (const ev of timeline.events) {
			if (ev.data.eventType === 'thinking') {
				sessionThinkingEvents++;
				sessionThinkingChars += (ev.data as { thinking: string }).thinking.length;
			}

			if (ev.data.eventType === 'user_message') {
				const text = (ev.data as { text: string }).text;
				if (!isHarnessSkillLoadMessage(text)) flush();
				continue;
			}

			if (ev.data.eventType === 'tool_call') {
				const tc = ev.data as ToolCallEvent;
				if (tc.toolName === 'Skill') {
					flush();
					const skillName = (tc.input as Record<string, unknown>).skill;
					if (typeof skillName === 'string') {
						const cur = skillUsage.get(skillName) || {
							count: 0,
							lastUsed: '',
							tokensGenerated: 0,
							costGenerated: 0
						};
						cur.count++;
						if (s.startedAt > cur.lastUsed) cur.lastUsed = s.startedAt;
						skillUsage.set(skillName, cur);
						activeSkill = skillName;
					}
					continue;
				}
				if (tc.toolName.startsWith('mcp__')) {
					const parts = tc.toolName.split('__');
					if (parts.length >= 3) {
						const server = parts[1];
						const cur = mcpUsage.get(server) || {
							count: 0,
							lastUsed: '',
							tools: new Set<string>()
						};
						cur.count++;
						cur.tools.add(parts.slice(2).join('__'));
						if (s.startedAt > cur.lastUsed) cur.lastUsed = s.startedAt;
						mcpUsage.set(server, cur);
					}
				}
			}

			// Charge this event's cost to the active skill, if any.
			if (activeSkill && ev.tokens) {
				activeTokens +=
					ev.tokens.input +
					ev.tokens.output +
					ev.tokens.cacheRead +
					ev.tokens.cacheCreation;
				activeCost += estimateCost(
					s.model,
					ev.tokens.input,
					ev.tokens.output,
					ev.tokens.cacheRead,
					ev.tokens.cacheCreation
				);
			}
		}
		flush();

		// Bucket the session by how often thinking ran. Many turns with thinking
		// = high effort. Sparse = medium. Zero = low (or fast mode).
		void sessionThinkingChars;
		if (sessionThinkingEvents >= 10) effortBuckets.high++;
		else if (sessionThinkingEvents >= 1) effortBuckets.medium++;
		else effortBuckets.low++;
	}

	for (const sk of skills) {
		const u = skillUsage.get(sk.name);
		if (u) {
			sk.invocationCount = u.count;
			sk.lastUsed = u.lastUsed;
			sk.tokensGenerated = u.tokensGenerated;
			sk.costGenerated = u.costGenerated;
		}
	}

	const mcpServers: OverheadFile[] = [...mcpUsage.entries()].map(([server, u]) => ({
		name: server,
		path: '',
		// At least the tools we observed are loaded; the system prompt may have more.
		tokensEst: Math.max(u.tools.size, 1) * TOKENS_PER_MCP_TOOL,
		invocationCount: u.count,
		lastUsed: u.lastUsed
	}));
	mcpServers.sort((a, b) => b.tokensEst - a.tokensEst);

	const claudeMdTokens = claudeMd.reduce((s, f) => s + f.tokensEst, 0);
	const skillsTokens = skills.reduce((s, f) => s + f.tokensEst, 0);
	const mcpTokens = mcpServers.reduce((s, f) => s + f.tokensEst, 0);
	const setupTokens = claudeMdTokens + skillsTokens + mcpTokens;

	// Use the mode model from the sample to price the overhead. Default to Sonnet.
	const modelCounts = new Map<string, number>();
	for (const s of sample) modelCounts.set(s.model, (modelCounts.get(s.model) || 0) + 1);
	let modeModel = 'claude-sonnet-4-5-20250929';
	let modeCount = 0;
	for (const [m, c] of modelCounts) {
		if (c > modeCount && m) {
			modeCount = c;
			modeModel = m;
		}
	}
	const pricing = pricingForModel(modeModel);

	const costPerSessionFresh = (setupTokens * pricing.cacheCreation) / 1_000_000;
	const costPerSessionCached = (setupTokens * pricing.cacheRead) / 1_000_000;

	const sessionsPerMonth = daysBack > 0 ? recent.length * (30 / daysBack) : 0;
	const monthlyCachedCost = costPerSessionCached * sessionsPerMonth;

	const recommendations: OverheadRecommendation[] = [];

	for (const sk of skills) {
		if (sk.invocationCount === 0 && sk.tokensEst >= 200) {
			const monthlySavings =
				(sk.tokensEst * pricing.cacheRead * sessionsPerMonth) / 1_000_000;
			recommendations.push({
				kind: 'unused-skill',
				title: `Skill "${sk.name}" never invoked`,
				detail: `${sk.tokensEst.toLocaleString()} tokens loaded into ${Math.round(sessionsPerMonth)} sessions/month. Move out of ~/.claude/skills/ to disable.`,
				monthlySavingsUsd: monthlySavings,
				severity: monthlySavings >= 0.5 ? 'warning' : 'info'
			});
		}
	}

	for (const mcp of mcpServers) {
		if (mcp.invocationCount === 0) {
			const monthlySavings =
				(mcp.tokensEst * pricing.cacheRead * sessionsPerMonth) / 1_000_000;
			recommendations.push({
				kind: 'unused-mcp',
				title: `MCP "${mcp.name}" connected but unused`,
				detail: `~${mcp.tokensEst.toLocaleString()} tokens of tool definitions per session. Disconnect to reclaim.`,
				monthlySavingsUsd: monthlySavings,
				severity: monthlySavings >= 1 ? 'critical' : 'warning'
			});
		}
	}

	for (const cm of claudeMd) {
		if (cm.tokensEst >= 1500) {
			const trimTarget = 500;
			const monthlySavings =
				((cm.tokensEst - trimTarget) * pricing.cacheRead * sessionsPerMonth) / 1_000_000;
			recommendations.push({
				kind: 'large-claude-md',
				title: `${cm.name} is ${cm.tokensEst.toLocaleString()} tokens`,
				detail: `Trimming to ~${trimTarget} tokens saves ~$${monthlySavings.toFixed(2)}/month at cached load.`,
				monthlySavingsUsd: monthlySavings,
				severity: cm.tokensEst >= 3000 ? 'warning' : 'info'
			});
		}
	}

	if (settings.effortLevel === 'high') {
		recommendations.push({
			kind: 'effort',
			title: 'effortLevel = "high" — extended thinking always on',
			detail: 'High effort spends extra output tokens on thinking before every reply. Switch to "medium" or "low" if your sessions are mostly mechanical edits.',
			monthlySavingsUsd: 0,
			severity: 'info'
		});
	}

	recommendations.sort((a, b) => b.monthlySavingsUsd - a.monthlySavingsUsd);

	// Re-sort skills: invoked-and-expensive first, then by static token weight.
	skills.sort((a, b) => {
		const aSpent = a.costGenerated || 0;
		const bSpent = b.costGenerated || 0;
		if (aSpent !== bSpent) return bSpent - aSpent;
		return b.tokensEst - a.tokensEst;
	});

	effortBuckets.configured = settings.effortLevel;

	const result: OverheadAnalysis = {
		claudeMd,
		skills,
		mcpServers,
		hooks: settings.hooks,
		effortLevel: settings.effortLevel,
		effort: effortBuckets,
		totals: {
			setupTokens,
			sessionsAnalyzed: sample.length,
			daysAnalyzed: daysBack,
			sessionsPerMonth,
			costPerSessionFresh,
			costPerSessionCached,
			monthlyCachedCost
		},
		recommendations
	};

	cache.set(cacheKey, { data: result, timestamp: Date.now() });
	return result;
}

/**
 * Per-session overhead view: which CLAUDE.md applied, which skills were invoked
 * (with $ generated), which MCP servers were touched, and observed thinking
 * effort. Used by the session detail page so the user can see "what cost what"
 * without leaving the timeline.
 */
export async function analyzeSessionOverhead(
	timeline: SessionTimeline
): Promise<SessionOverhead> {
	const cwd = timeline.summary.cwd;
	const claudeMd = await scanClaudeMd(cwd ? [cwd] : []);

	const skillUsage = new Map<
		string,
		{ count: number; costGenerated: number; tokensGenerated: number }
	>();
	const mcpUsage = new Map<string, { count: number; tools: Set<string> }>();

	let activeSkill: string | null = null;
	let activeTokens = 0;
	let activeCost = 0;
	const flush = () => {
		if (activeSkill) {
			const u = skillUsage.get(activeSkill);
			if (u) {
				u.tokensGenerated += activeTokens;
				u.costGenerated += activeCost;
			}
		}
		activeSkill = null;
		activeTokens = 0;
		activeCost = 0;
	};

	let thinkingChars = 0;
	let thinkingEvents = 0;

	for (const ev of timeline.events) {
		if (ev.data.eventType === 'thinking') {
			thinkingEvents++;
			thinkingChars += (ev.data as { thinking: string }).thinking.length;
		}

		if (ev.data.eventType === 'user_message') {
			const text = (ev.data as { text: string }).text;
			if (!isHarnessSkillLoadMessage(text)) flush();
			continue;
		}
		if (ev.data.eventType === 'tool_call') {
			const tc = ev.data as ToolCallEvent;
			if (tc.toolName === 'Skill') {
				flush();
				const skillName = (tc.input as Record<string, unknown>).skill;
				if (typeof skillName === 'string') {
					const cur = skillUsage.get(skillName) || {
						count: 0,
						costGenerated: 0,
						tokensGenerated: 0
					};
					cur.count++;
					skillUsage.set(skillName, cur);
					activeSkill = skillName;
				}
				continue;
			}
			if (tc.toolName.startsWith('mcp__')) {
				const parts = tc.toolName.split('__');
				if (parts.length >= 3) {
					const server = parts[1];
					const tool = parts.slice(2).join('__');
					const cur = mcpUsage.get(server) || { count: 0, tools: new Set<string>() };
					cur.count++;
					cur.tools.add(tool);
					mcpUsage.set(server, cur);
				}
			}
		}

		if (activeSkill && ev.tokens) {
			activeTokens +=
				ev.tokens.input + ev.tokens.output + ev.tokens.cacheRead + ev.tokens.cacheCreation;
			activeCost += estimateCost(
				timeline.summary.model,
				ev.tokens.input,
				ev.tokens.output,
				ev.tokens.cacheRead,
				ev.tokens.cacheCreation
			);
		}
	}
	flush();

	const skillsInvoked = [...skillUsage.entries()]
		.map(([name, u]) => ({
			name,
			count: u.count,
			costGenerated: u.costGenerated,
			tokensGenerated: u.tokensGenerated
		}))
		.sort((a, b) => b.costGenerated - a.costGenerated);

	const mcpUsed = [...mcpUsage.entries()]
		.map(([server, u]) => ({ server, count: u.count, tools: [...u.tools] }))
		.sort((a, b) => b.count - a.count);

	const bucket: 'low' | 'medium' | 'high' =
		thinkingEvents >= 10 ? 'high' : thinkingEvents >= 1 ? 'medium' : 'low';

	return {
		claudeMd,
		skillsInvoked,
		mcpUsed,
		// `ratio` here is kept for backwards-compat in the type but reused as
		// "thinking events count" — easier to interpret than a fractional ratio
		// when content is encrypted.
		effort: { bucket, thinkingChars, ratio: thinkingEvents }
	};
}
